### ISSUE TITLE
CMake 版本要求是不是太高了一点？

### ISSUE THREAD

**Issue by hosiet** [linuxflyos/flyos-campus-network#1]
如题，Debian 9 里最高只有 CMake 3.7.2，无法正常编译代码。望能考虑不要使用过新的功能，将 CMake 要求降低一点。

**Comment by xiayesuifeng** [comment]
这个，，，，自己改下CMakeLists.txt就好，版本号等是clion自动生成的，clion用的是他自己内建的cmake，但是那个版本号只是一个最低版本依赖而已，版本号降下一点还是可以的。cmakelist一打开，版本号很好认的，直接改下就好
